// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRCyawJiSjsKIZ9NzPihDVBTbrNT8CMBQ',
    appId: '1:875461394072:web:3811c56fa09a014c5c9aed',
    messagingSenderId: '875461394072',
    projectId: 'mobile-jejakrasa',
    authDomain: 'mobile-jejakrasa.firebaseapp.com',
    storageBucket: 'mobile-jejakrasa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVyd1ji7s3vY-Vqr9TLpXmEZl_SP0-PMk',
    appId: '1:875461394072:android:b29b09b07904c83f5c9aed',
    messagingSenderId: '875461394072',
    projectId: 'mobile-jejakrasa',
    storageBucket: 'mobile-jejakrasa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR_VatAiXdkVxwyhzl570WGMHU3qQgDZI',
    appId: '1:875461394072:ios:c34317a2ef2752e35c9aed',
    messagingSenderId: '875461394072',
    projectId: 'mobile-jejakrasa',
    storageBucket: 'mobile-jejakrasa.firebasestorage.app',
    iosBundleId: 'com.example.jejakrasaMobileDatabase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR_VatAiXdkVxwyhzl570WGMHU3qQgDZI',
    appId: '1:875461394072:ios:c34317a2ef2752e35c9aed',
    messagingSenderId: '875461394072',
    projectId: 'mobile-jejakrasa',
    storageBucket: 'mobile-jejakrasa.firebasestorage.app',
    iosBundleId: 'com.example.jejakrasaMobileDatabase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRCyawJiSjsKIZ9NzPihDVBTbrNT8CMBQ',
    appId: '1:875461394072:web:41ff64f30ec75e4c5c9aed',
    messagingSenderId: '875461394072',
    projectId: 'mobile-jejakrasa',
    authDomain: 'mobile-jejakrasa.firebaseapp.com',
    storageBucket: 'mobile-jejakrasa.firebasestorage.app',
  );
}
